// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1BlendV8HemiNoiseResponse } from './types.gen';

export class V1Service {
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getApiV1BlendV8HemiNoise(): CancelablePromise<GetApiV1BlendV8HemiNoiseResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/Blend.V8Hemi/noise',
            errors: {
                401: 'The resource is protected and requires an authentication token'
            }
        });
    }
    
}